## Tensorflow的feature_column的语法演示

内容回顾：
tf.feature_column用于将原始数据转换成model所需要的格式，包含如下方法：
* 数值列（Numeric column）：tf.feature_column.numeric_column
* 分桶列（Bucketized column）：tf.feature_column.bucketized_column
* 分类标识列(Categorical identity column)：tf.feature_column.categorical_column_with_identity
* 分类词汇列(Categorical vocabulary column)：tf.feature_column.categorical_column_with_vocabulary_list
* 哈希处理的列(Hashed Column)：tf.feature_column.categorical_column_with_hash_bucket
* 组合列(Crossed column)：tf.feature_column.crossed_column
* 指标列(Indicator Column)：tf.feature_column.indicator_column
* 嵌入列(Embedding Column)：tf.feature_column.embedding_column
* 共享Embedding：tf.feature_column.shared_embeddings
* 加权分类特征：tf.feature_column.weighted_categorical_column

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers

tf.keras.backend.set_floatx('float64')

### 准备dict数据

In [2]:
df = pd.DataFrame({'marks': [55,21,63,88,74,54,95,41,84,52],
        'grade': ['average','poor','average','good','good','average','good','average','good','average'],
        'point': ['c','f','c+','b+','b','c','a','d+','b+','c']})
df

marks    grade point
0     55  average     c
1     21     poor     f
2     63  average    c+
3     88     good    b+
4     74     good     b
5     54  average     c
6     95     good     a
7     41  average    d+
8     84     good    b+
9     52  average     c

In [3]:
df["marks"] = df["marks"].astype("float64")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   marks   10 non-null     float64
 1   grade   10 non-null     object 
 2   point   10 non-null     object 
dtypes: float64(1), object(2)
memory usage: 368.0+ bytes


In [4]:
data = dict(df)
data

{'marks': 0    55.0
 1    21.0
 2    63.0
 3    88.0
 4    74.0
 5    54.0
 6    95.0
 7    41.0
 8    84.0
 9    52.0
 Name: marks, dtype: float64,
 'grade': 0    average
 1       poor
 2    average
 3       good
 4       good
 5    average
 6       good
 7    average
 8       good
 9    average
 Name: grade, dtype: object,
 'point': 0     c
 1     f
 2    c+
 3    b+
 4     b
 5     c
 6     a
 7    d+
 8    b+
 9     c
 Name: point, dtype: object}

In [5]:
def demo(feature_column):
    feature_layer = layers.DenseFeatures(feature_column)
    print(feature_layer(data).numpy())

### 1. Numeric columns

In [6]:
data["marks"]

0    55.0
1    21.0
2    63.0
3    88.0
4    74.0
5    54.0
6    95.0
7    41.0
8    84.0
9    52.0
Name: marks, dtype: float64

In [7]:
marks = feature_column.numeric_column("marks")
demo(marks)

[[55.]
 [21.]
 [63.]
 [88.]
 [74.]
 [54.]
 [95.]
 [41.]
 [84.]
 [52.]]


### 2. Bucketized columns

In [8]:
data["marks"]

0    55.0
1    21.0
2    63.0
3    88.0
4    74.0
5    54.0
6    95.0
7    41.0
8    84.0
9    52.0
Name: marks, dtype: float64

In [9]:
marks

NumericColumn(key='marks', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)

In [10]:
marks_buckets = feature_column.bucketized_column(
    marks, boundaries=[30,40,50,60,70,80,90])
demo(marks_buckets)

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


### 3. Indicator columns

In [11]:
data["grade"]

0    average
1       poor
2    average
3       good
4       good
5    average
6       good
7    average
8       good
9    average
Name: grade, dtype: object

In [12]:
grade = feature_column.categorical_column_with_vocabulary_list(
      'grade', ['poor', 'average', 'good'])
grade

VocabularyListCategoricalColumn(key='grade', vocabulary_list=('poor', 'average', 'good'), dtype=tf.string, default_value=-1, num_oov_buckets=0)

In [13]:
grade_one_hot = feature_column.indicator_column(grade)
demo(grade_one_hot)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


### 4. Embedding columns

In [14]:
data["point"]

0     c
1     f
2    c+
3    b+
4     b
5     c
6     a
7    d+
8    b+
9     c
Name: point, dtype: object

In [15]:
point = feature_column.categorical_column_with_vocabulary_list(
    "point", df["point"].unique())

In [16]:
# categorical_column变成one-hot
point_one_hot = feature_column.indicator_column(point)
demo(point_one_hot)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [17]:
# categorical_column变成embedding
point_embedding = feature_column.embedding_column(point, dimension=3)
demo(point_embedding)

[[ 0.4075148   0.15946811  0.70163053]
 [-0.66768515 -0.553674    0.0775062 ]
 [-0.14868784 -0.7745282  -0.20978285]
 [-0.2074475   0.0967237   0.12427108]
 [ 0.15544215 -0.43846348 -0.22467692]
 [ 0.4075148   0.15946811  0.70163053]
 [-1.0620091   0.28062528  0.64527065]
 [-0.23770526 -0.08222763 -0.7725818 ]
 [-0.2074475   0.0967237   0.12427108]
 [ 0.4075148   0.15946811  0.70163053]]


### 5. Hashed feature columns

In [18]:
data["point"]

0     c
1     f
2    c+
3    b+
4     b
5     c
6     a
7    d+
8    b+
9     c
Name: point, dtype: object

In [19]:
point_hashed = feature_column.categorical_column_with_hash_bucket(
      'point', hash_bucket_size=3)
demo(feature_column.indicator_column(point_hashed))

[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


### 6. Crossed feature columns

In [20]:
marks_buckets

BucketizedColumn(source_column=NumericColumn(key='marks', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(30, 40, 50, 60, 70, 80, 90))

In [21]:
grade

VocabularyListCategoricalColumn(key='grade', vocabulary_list=('poor', 'average', 'good'), dtype=tf.string, default_value=-1, num_oov_buckets=0)

In [23]:
crossed_feature = feature_column.crossed_column(
    [marks_buckets, grade], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
