## Tensorflow常见Layer层介绍

# Tensorflow常见的Layer层介绍：

1. tf.keras.layers.Dense
2. tf.keras.layers.DenseFeatures
3. tf.keras.layers.Flatten
4. tf.keras.layers.ReLU
5. tf.keras.layers.Multiply
6. tf.keras.layers.Concatenate
7. tf.keras.layers.Average
8. tf.keras.layers.Dot
9. tf.keras.layers.Lambda
10. tf.keras.layers.Dropout
11. tf.keras.layers.Embedding

In [1]:
import tensorflow as tf
import numpy as np

tf.keras.backend.set_floatx('float64')

### 1. tf.keras.layers.Dense

即全连接层，实现了函数output = activation(dot(input, kernel) + bias)

#### 中间层：全连接层

In [ ]:
layer = tf.keras.layers.Dense(5, activation='relu')
inputs = tf.random.uniform(shape=(10, 20))
layer(inputs)

#### 输出层：二分类sigmoid层

In [ ]:
layer = tf.keras.layers.Dense(1, activation='sigmoid')
inputs = tf.random.uniform(shape=(10, 20))
layer(inputs)

#### 输出层：多分类softmax层

In [ ]:
layer = tf.keras.layers.Dense(5, activation='softmax')
inputs = tf.random.uniform(shape=(10, 20))
layer(inputs)

### 2. tf.keras.layers.DenseFeatures
输入feature_columns，产出dense Tensor

In [ ]:
data = {"age" : [10, 20, 30, 40, 50]}
feature_columns = [tf.feature_column.numeric_column("age", normalizer_fn=lambda x : (x-30)/(50-10))]

layer = tf.keras.layers.DenseFeatures(feature_columns)
layer(data)

### 3. tf.keras.layers.Flatten

In [ ]:
data = np.random.rand(5, 2, 2)
data.shape

In [ ]:
layer = tf.keras.layers.Flatten()
layer(data)

### 4. tf.keras.layers.ReLU

大于零的数字还是本身，小于零的全变成0

In [ ]:
layer = tf.keras.layers.ReLU()
layer([-1, -2, -3, 0, 1, 2, 3])

### 5. tf.keras.layers.Multiply

相同形状的矩阵，对应元素相乘的乘法

In [ ]:
data = np.arange(10).reshape(5, 2)
x1 = tf.keras.layers.Dense(3)(data)
x1

In [ ]:
data = np.arange(10, 20).reshape(5, 2)
x2 = tf.keras.layers.Dense(3)(data)
x2

In [ ]:
multiplied = tf.keras.layers.Multiply()([x1, x2])
multiplied.shape

### 6. tf.keras.layers.Concatenate

In [ ]:
x1 = tf.keras.layers.Dense(2)(np.arange(10).reshape(5, 2))
x1

In [ ]:
x2 = tf.keras.layers.Dense(2)(np.arange(10, 20).reshape(5, 2))
x2

In [ ]:
concatted = tf.keras.layers.Concatenate()([x1, x2])
concatted

### 7. tf.keras.layers.Average

还有类似的：
* tf.keras.layers.Minimum
* tf.keras.layers.Maximum
* tf.keras.layers.Subtract
* tf.keras.layers.Add

In [ ]:
x1 = np.ones((2, 2))
x2 = np.zeros((2, 2))

In [ ]:
tf.keras.layers.Average()([x1, x2])

In [ ]:
tf.keras.layers.Add()([x1, x2])

### 8. tf.keras.layers.Dot

两个形状是：(batch_size, n)，点积结果是(batch_size, 1)，其中第i个元素是a[i]和b[i]的点积

In [ ]:
x1 = tf.keras.layers.Dense(3)(np.arange(10).reshape(5, 2))
x1

In [ ]:
x2 = tf.keras.layers.Dense(3)(np.arange(10, 20).reshape(5, 2))
x2

In [ ]:
dotted = tf.keras.layers.Dot(axes=1)([x1, x2])
dotted

### 9. tf.keras.layers.Lambda

将任意表达式函数，封装成Layer对象

In [ ]:
data = np.arange(12).reshape(3,4)
data

In [ ]:
layer = tf.keras.layers.Lambda(lambda x: x * 2)

layer(data)

### 10. tf.keras.layers.Dropout

In [ ]:
data = np.arange(10).reshape(5, 2).astype(np.float64)
data

使用随机的概率将输入数据设置成0，降低过拟合

In [ ]:
layer = tf.keras.layers.Dropout(rate=0.3)
layer(data, training=True)

### 11. tf.keras.layers.Embedding

解释：
* 输入一个大小为8的一维数组，每个都是ID数字；
* 目的是把每个数字，都表示成一个embedding向量，向量的dim是可调整的参数

In [5]:
# 原始数据，正式ID列表，注意100是这里的最大值
data = np.random.randint(100, size=(8, 3))
data

array([[21, 68, 48],
       [46, 78, 33],
       [67, 15, 29],
       [ 8, 23, 52],
       [ 0,  6, 41],
       [87,  2, 58],
       [63, 46, 87],
       [19, 14, 89]])

In [29]:
# 不定长列表
data = tf.ragged.constant(
    [
        [21, 68, 48],
        [46, 78],
        [67]   
    ]
)

In [30]:
data

<tf.RaggedTensor [[21, 68, 48], [46, 78], [67]]>

In [31]:
tf.math.reduce_mean(data, axis=1).numpy()

array([45.66666667, 62.        , 67.        ])

In [32]:
# 构造Embedding层，其中第一个参数100是ID词汇表的大小，第二个5是每个embedding的维度，
layer = tf.keras.layers.Embedding(100, 5, mask_zero=True)

In [34]:
layer(data).shape

TensorShape([3, None, 5])

In [35]:
tf.math.reduce_mean(layer(data), axis=1)

<tf.Tensor: shape=(3, 5), dtype=float64, numpy=
array([[ 0.01449433, -0.00456918,  0.00115098,  0.02015025,  0.00558433],
       [ 0.00446629,  0.01671126, -0.01464904, -0.00302114, -0.04203403],
       [ 0.03610629, -0.02131151,  0.03470666,  0.03844354, -0.044591  ]])>

In [1]:
import numpy as np

In [2]:
x = np.array(
    [
        [21., 68., 48.],
        [46., 78., 99.],
        [67., 88., 66]   
    ]
)

In [3]:
y = np.array([1,0,1])

In [4]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(100, 5, mask_zero=True))
model.add(tf.keras.layers.Dense(1))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(x, y)

NameError: name 'tf' is not defined

输出为(8, 5)，意思是给每个ID，都产出了一个5维度的Embedding向量